baseURL: https://www.jeanmonnet-ista.eu/
title: ISTA-EU | Innovative STEM teaching practices in Albania towards European Integration
theme: educenter-hugo
paginate: '6'
summaryLength: '10'
disqusShortname: ISTPATEI
disableLanguages: [yes]
params:
  address: Sulejman Delvina St, Tirana, Albania
  author: Jean Monnet PTU
  contact_form_action: '#'
  description: This is the website for Innovative STEM teaching practices in Albania towards European Integration under project ERASMUS-JMO-2022-HEI-TCH-RSCH
  email: istpatei@fimif.edu.al
  google_analitycs_id: ''
  logo: images/logo.png
  map:
    enable: yes
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places
    map_latitude: '41.32060655896605'
    map_longitude: '19.804920084552872'
    map_marker: images/marker.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/slick/slick.css
      - link: plugins/animate/animate.css
      - link: plugins/venobox/venobox.css
      - link: plugins/themify-icons/themify-icons.css
    js:
      - link: plugins/jQuery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/venobox/venobox.min.js
      - link: plugins/filterizr/jquery.filterizr.min.js
      - link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: images/preloader.gif
  social:
    - icon: ti-facebook
      link: '#'
      title: facebook
    - icon: ti-twitter-alt
      link: '#'
      title: twitter
    - icon: ti-instagram
      link: '#'
      title: instagram
    - icon: ti-github
      link: '#'
      title: github
    - icon: ti-linkedin
      link: '#'
      title: linkedin
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2022 Website mantained by [Jean Monnet PTU Team](https://www.jeanmonnet-ista.eu/)
    home: Home
    languageCode: en-us
    languageName: En
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Teaching
          url: course/
          weight: 1
        - name: Events
          url: event/
          weight: 1
        - name: Lecturers
          url: teachers/
          weight: 1
        - name: Contacts
          url: contact/
          weight: 1
    weight: 1
